services:
  LabDatabase:
    image: mysql:8
    ports:
      - 4500:4500
    expose:
      - 4500
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=Lab
    volumes:
      - ./database/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
