services:
  LabDatabase:
    image: mysql:8
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=Lab
    volumes:
      - ./database/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/seed.sql
